name: get_followers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout repository content
        with:
          ref: main
          fetch-depth: '0'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install python version
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        env: 
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          python get-followers.py
  
      - name: Pull Remote Changes
        run: git pull
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a --allow-empty
        
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
